// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Employee.Models;

public partial class Employee
{

    public int EmpId { get; set; }

    [Required(ErrorMessage = "Employee Name is required.")]
    [StringLength(50, ErrorMessage = "Employee Name must not exceed 50 characters.")]
    public string Ename { get; set; }

    [Required(ErrorMessage = "Department Name is required.")]
    [StringLength(50, ErrorMessage = "Department Name must not exceed 50 characters.")]
    public string DeptName { get; set; }

    [Required(ErrorMessage = "Age is required.")]
    [Range(18, 99, ErrorMessage = "Age must be between 18 and 99.")]
    public int Age { get; set; }

    [Required(ErrorMessage = "Salary is required.")]
    [Range(0, int.MaxValue, ErrorMessage = "Salary must be a non-negative value.")]
    public int Salary { get; set; }

    public bool? IsDeleted { get; set; }

    public string Skills { get; set; }

    public virtual ICollection<Skill> SkillsNavigation { get; set; } = new List<Skill>();
}