// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Employee.Models;

public partial class Employee
{
    public int EmpId { get; set; }

    public string Ename { get; set; }

    public string DeptName { get; set; }

    public int? Age { get; set; }

    public int? Salary { get; set; }

    public bool? IsDeleted { get; set; }

    public string Skills { get; set; }
}