// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Employee.Models
{
    public partial class GetDeletedRecordsResult
    {
        public int EmpID { get; set; }
        public string EName { get; set; }
        public string DeptName { get; set; }
        public int? Age { get; set; }
        public int? Salary { get; set; }
        public bool? IsDeleted { get; set; }
        public string Skills { get; set; }
    }
}
