// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Employee.Models
{
    public partial class GetEmployeeByIdResult
    {
        [Required(ErrorMessage = "Employee ID is required.")]
        public int EmpID { get; set; }

        [Required(ErrorMessage = "Employee Name is required.")]
        [StringLength(50, ErrorMessage = "Employee Name must not exceed 50 characters.")]
        public string EName { get; set; }

        [Required(ErrorMessage = "Department Name is required.")]
        [StringLength(50, ErrorMessage = "Department Name must not exceed 50 characters.")]
        public string DeptName { get; set; }

        [Range(18, 99, ErrorMessage = "Age must be between 18 and 99.")]
        public int Age { get; set; }

        [Range(0, int.MaxValue, ErrorMessage = "Salary must be a non-negative value.")]
        public int Salary { get; set; }

        public bool? IsDeleted { get; set; }
        public string Skills { get; set; }
    }
}
