// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Employee.Models
{
    public partial class GetSkillsForEmployeeResult
    {
        public int SkillID { get; set; }
        public string SkillName { get; set; }
    }
}
