// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Employee.Models;

public partial class Skill
{
    public int SkillId { get; set; }

    public string SkillName { get; set; }

    public virtual ICollection<Employee> Emps { get; set; } = new List<Employee>();
}